import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  try {
    console.log('🌱 Starting seed...')
    
    // Clear existing data
    await prisma.student.deleteMany({})
    console.log('🧹 Cleared existing students')

    // Insert students with individual subject scores
    const students = [
      {
        examID: "EXM-2024-001",
        dateOfBirth: new Date("2003-12-13"),
        studentNationalID: "1000000000001",
        firstName: "Abebe",
        lastName: "Kebede",
        email: "abebe@example.com",
        phone: "+25191110001",
        region: "Addis Ababa",
        examResults: { mathematics: 172, english: 188, physics: 83, chemistry: 83, biology: 90, total: 616 },
        gender: "Male",
        disability: "none",
        photo: "https://randomuser.me/api/portraits/men/1.jpg",
        school: "Addis Ababa University",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-003",
        dateOfBirth: new Date("2004-12-11"),
        studentNationalID: "1000000000003",
        firstName: "Habtamu",
        lastName: "Tadesse",
        email: "habtamu@example.com",
        phone: "+25191110003",
        region: "Oromia",
        examResults: { mathematics: 176, english: 167, physics: 70, chemistry: 71, biology: 70, total: 554 },
        gender: "Female",
        disability: "none",
        photo: "https://randomuser.me/api/portraits/women/2.jpg",
        school: "Bahir Dar University",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-005",
        dateOfBirth: new Date("2004-05-27"),
        studentNationalID: "1000000000005",
        firstName: "Senayit",
        lastName: "Wolde",
        email: "senayit@example.com",
        phone: "+25191110005",
        region: "Amhara",
        examResults: { mathematics: 198, english: 172, physics: 99, chemistry: 66, biology: 70, total: 605 },
        gender: "Male",
        disability: "none",
        photo: "https://randomuser.me/api/portraits/men/3.jpg",
        school: "Hawassa University",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-007",
        dateOfBirth: new Date("2003-11-07"),
        studentNationalID: "1000000000007",
        firstName: "Bruk",
        lastName: "Assefa",
        email: "bruk@example.com",
        phone: "+25191110007",
        region: "SNNPR",
        examResults: { mathematics: 184, english: 196, physics: 65, chemistry: 91, biology: 99, total: 635 },
        gender: "Female",
        disability: "none",
        photo: "https://randomuser.me/api/portraits/women/4.jpg",
        school: "St. Joseph School",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-009",
        dateOfBirth: new Date("2005-04-01"),
        studentNationalID: "1000000000009",
        firstName: "Betelhem",
        lastName: "Mekonnen",
        email: "betelhem@example.com",
        phone: "+25191110009",
        region: "Sidama",
        examResults: { mathematics: 163, english: 183, physics: 74, chemistry: 64, biology: 81, total: 565 },
        gender: "Male",
        disability: "none",
        photo: "https://randomuser.me/api/portraits/men/5.jpg",
        school: "Bishoftu Preparatory",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-011",
        dateOfBirth: new Date("2005-08-19"),
        studentNationalID: "1000000000011",
        firstName: "Dawit",
        lastName: "Hailu",
        email: "dawit@example.com",
        phone: "+25191110011",
        region: "Dire Dawa",
        examResults: { mathematics: 188, english: 181, physics: 89, chemistry: 94, biology: 76, total: 628 },
        gender: "Female",
        disability: "visual",
        photo: "https://randomuser.me/api/portraits/women/6.jpg",
        school: "Fasiladas School",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-013",
        dateOfBirth: new Date("2003-11-03"),
        studentNationalID: "1000000000013",
        firstName: "Fasika",
        lastName: "Girma",
        email: "fasika@example.com",
        phone: "+25191110013",
        region: "Tigray",
        examResults: { mathematics: 177, english: 166, physics: 66, chemistry: 60, biology: 91, total: 560 },
        gender: "Male",
        disability: "hearing",
        photo: "https://randomuser.me/api/portraits/men/7.jpg",
        school: "Kalamino Special High School",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-015",
        dateOfBirth: new Date("2003-04-02"),
        studentNationalID: "1000000000015",
        firstName: "Yosef",
        lastName: "Bekele",
        email: "yosef@example.com",
        phone: "+25191110015",
        region: "Harari",
        examResults: { mathematics: 187, english: 176, physics: 92, chemistry: 82, biology: 88, total: 625 },
        gender: "Female",
        disability: "physical",
        photo: "https://randomuser.me/api/portraits/women/8.jpg",
        school: "Dire Dawa Preparatory",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-017",
        dateOfBirth: new Date("2003-03-05"),
        studentNationalID: "1000000000017",
        firstName: "Mekdes",
        lastName: "Alemu",
        email: "mekdes@example.com",
        phone: "+25191110017",
        region: "Somali",
        examResults: { mathematics: 187, english: 175, physics: 75, chemistry: 77, biology: 87, total: 601 },
        gender: "Male",
        disability: "none",
        photo: "https://randomuser.me/api/portraits/men/9.jpg",
        school: "Hawassa Tabor",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-019",
        dateOfBirth: new Date("2005-03-10"),
        studentNationalID: "1000000000019",
        firstName: "Samuel",
        lastName: "Tilahun",
        email: "samuel@example.com",
        phone: "+25191110019",
        region: "Afar",
        examResults: { mathematics: 196, english: 175, physics: 80, chemistry: 82, biology: 86, total: 619 },
        gender: "Female",
        disability: "none",
        photo: "https://randomuser.me/api/portraits/women/10.jpg",
        school: "Yirgalem School",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-021",
        dateOfBirth: new Date("2005-06-19"),
        studentNationalID: "1000000000021",
        firstName: "Rahel",
        lastName: "Dessie",
        email: "rahel@example.com",
        phone: "+25191110021",
        region: "Benshangul-Gumuz",
        examResults: { mathematics: 195, english: 162, physics: 90, chemistry: 78, biology: 90, total: 615 },
        gender: "Male",
        disability: "none",
        photo: "https://randomuser.me/api/portraits/men/11.jpg",
        school: "Ethio-Parents School",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-023",
        dateOfBirth: new Date("2003-07-10"),
        studentNationalID: "1000000000023",
        firstName: "Kaleb",
        lastName: "Woldemariam",
        email: "kaleb@example.com",
        phone: "+25191110023",
        region: "Gambela",
        examResults: { mathematics: 176, english: 185, physics: 64, chemistry: 78, biology: 69, total: 572 },
        gender: "Female",
        disability: "none",
        photo: "https://randomuser.me/api/portraits/women/12.jpg",
        school: "Bahir Dar Academy",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-025",
        dateOfBirth: new Date("2003-04-28"),
        studentNationalID: "1000000000025",
        firstName: "Ermias",
        lastName: "Tesfaye",
        email: "ermias@example.com",
        phone: "+25191110025",
        region: "Addis Ababa",
        examResults: { mathematics: 187, english: 194, physics: 97, chemistry: 61, biology: 88, total: 627 },
        gender: "Male",
        disability: "none",
        photo: "https://randomuser.me/api/portraits/men/13.jpg",
        school: "Addis Ababa University",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-027",
        dateOfBirth: new Date("2003-07-20"),
        studentNationalID: "1000000000027",
        firstName: "Hirut",
        lastName: "Haile",
        email: "hirut@example.com",
        phone: "+25191110027",
        region: "Oromia",
        examResults: { mathematics: 164, english: 192, physics: 97, chemistry: 60, biology: 79, total: 592 },
        gender: "Female",
        disability: "visual",
        photo: "https://randomuser.me/api/portraits/women/14.jpg",
        school: "Bahir Dar University",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-029",
        dateOfBirth: new Date("2003-09-26"),
        studentNationalID: "1000000000029",
        firstName: "Tilahun",
        lastName: "Demeke",
        email: "tilahun@example.com",
        phone: "+25191110029",
        region: "Amhara",
        examResults: { mathematics: 198, english: 173, physics: 91, chemistry: 87, biology: 97, total: 646 },
        gender: "Male",
        disability: "hearing",
        photo: "https://randomuser.me/api/portraits/men/15.jpg",
        school: "Hawassa University",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-031",
        dateOfBirth: new Date("2003-02-11"),
        studentNationalID: "1000000000031",
        firstName: "Zinash",
        lastName: "Tekle",
        email: "zinash@example.com",
        phone: "+25191110031",
        region: "SNNPR",
        examResults: { mathematics: 184, english: 172, physics: 89, chemistry: 93, biology: 98, total: 636 },
        gender: "Female",
        disability: "physical",
        photo: "https://randomuser.me/api/portraits/women/16.jpg",
        school: "St. Joseph School",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-033",
        dateOfBirth: new Date("2004-04-10"),
        studentNationalID: "1000000000033",
        firstName: "Eyob",
        lastName: "Goshu",
        email: "eyob@example.com",
        phone: "+25191110033",
        region: "Sidama",
        examResults: { mathematics: 185, english: 166, physics: 89, chemistry: 75, biology: 86, total: 601 },
        gender: "Male",
        disability: "none",
        photo: "https://randomuser.me/api/portraits/men/17.jpg",
        school: "Bishoftu Preparatory",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-035",
        dateOfBirth: new Date("2005-04-10"),
        studentNationalID: "1000000000035",
        firstName: "Kidist",
        lastName: "Tadele",
        email: "kidist@example.com",
        phone: "+25191110035",
        region: "Dire Dawa",
        examResults: { mathematics: 161, english: 192, physics: 80, chemistry: 68, biology: 87, total: 588 },
        gender: "Female",
        disability: "none",
        photo: "https://randomuser.me/api/portraits/women/18.jpg",
        school: "Fasiladas School",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-037",
        dateOfBirth: new Date("2004-03-03"),
        studentNationalID: "1000000000037",
        firstName: "Solomon",
        lastName: "Worku",
        email: "solomon@example.com",
        phone: "+25191110037",
        region: "Tigray",
        examResults: { mathematics: 181, english: 172, physics: 70, chemistry: 68, biology: 69, total: 560 },
        gender: "Male",
        disability: "none",
        photo: "https://randomuser.me/api/portraits/men/19.jpg",
        school: "Kalamino Special High School",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-039",
        dateOfBirth: new Date("2004-02-06"),
        studentNationalID: "1000000000039",
        firstName: "Lidya",
        lastName: "Legesse",
        email: "lidya@example.com",
        phone: "+25191110039",
        region: "Harari",
        examResults: { mathematics: 161, english: 186, physics: 62, chemistry: 82, biology: 61, total: 552 },
        gender: "Female",
        disability: "none",
        photo: "https://randomuser.me/api/portraits/women/20.jpg",
        school: "Dire Dawa Preparatory",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-041",
        dateOfBirth: new Date("2004-10-19"),
        studentNationalID: "1000000000041",
        firstName: "Nahom",
        lastName: "Belay",
        email: "nahom@example.com",
        phone: "+25191110041",
        region: "Somali",
        examResults: { mathematics: 160, english: 190, physics: 87, chemistry: 65, biology: 96, total: 598 },
        gender: "Male",
        disability: "none",
        photo: "https://randomuser.me/api/portraits/men/21.jpg",
        school: "Hawassa Tabor",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-043",
        dateOfBirth: new Date("2003-11-23"),
        studentNationalID: "1000000000043",
        firstName: "Tsion",
        lastName: "Getachew",
        email: "tsion@example.com",
        phone: "+25191110043",
        region: "Afar",
        examResults: { mathematics: 178, english: 180, physics: 69, chemistry: 83, biology: 68, total: 578 },
        gender: "Female",
        disability: "visual",
        photo: "https://randomuser.me/api/portraits/women/22.jpg",
        school: "Yirgalem School",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-045",
        dateOfBirth: new Date("2004-10-21"),
        studentNationalID: "1000000000045",
        firstName: "Abel",
        lastName: "Zewde",
        email: "abel@example.com",
        phone: "+25191110045",
        region: "Benshangul-Gumuz",
        examResults: { mathematics: 192, english: 192, physics: 66, chemistry: 80, biology: 61, total: 591 },
        gender: "Male",
        disability: "hearing",
        photo: "https://randomuser.me/api/portraits/men/23.jpg",
        school: "Ethio-Parents School",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-047",
        dateOfBirth: new Date("2005-06-21"),
        studentNationalID: "1000000000047",
        firstName: "Ruth",
        lastName: "Ayele",
        email: "ruth@example.com",
        phone: "+25191110047",
        region: "Gambela",
        examResults: { mathematics: 160, english: 173, physics: 64, chemistry: 70, biology: 80, total: 547 },
        gender: "Female",
        disability: "physical",
        photo: "https://randomuser.me/api/portraits/women/24.jpg",
        school: "Bahir Dar Academy",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-049",
        dateOfBirth: new Date("2003-03-11"),
        studentNationalID: "1000000000049",
        firstName: "Binyam",
        lastName: "Mulugeta",
        email: "binyam@example.com",
        phone: "+25191110049",
        region: "Addis Ababa",
        examResults: { mathematics: 192, english: 175, physics: 82, chemistry: 75, biology: 63, total: 587 },
        gender: "Male",
        disability: "none",
        photo: "https://randomuser.me/api/portraits/men/25.jpg",
        school: "Addis Ababa University",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-051",
        dateOfBirth: new Date("2005-04-13"),
        studentNationalID: "1000000000051",
        firstName: "Helen",
        lastName: "Gedamu",
        email: "helen@example.com",
        phone: "+25191110051",
        region: "Oromia",
        examResults: { mathematics: 186, english: 161, physics: 60, chemistry: 60, biology: 85, total: 552 },
        gender: "Female",
        disability: "none",
        photo: "https://randomuser.me/api/portraits/women/26.jpg",
        school: "Bahir Dar University",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-053",
        dateOfBirth: new Date("2004-11-09"),
        studentNationalID: "1000000000053",
        firstName: "Henok",
        lastName: "Tsegaye",
        email: "henok@example.com",
        phone: "+25191110053",
        region: "Amhara",
        examResults: { mathematics: 189, english: 195, physics: 69, chemistry: 60, biology: 87, total: 600 },
        gender: "Male",
        disability: "none",
        photo: "https://randomuser.me/api/portraits/men/27.jpg",
        school: "Hawassa University",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-055",
        dateOfBirth: new Date("2003-02-28"),
        studentNationalID: "1000000000055",
        firstName: "Salem",
        lastName: "Kassa",
        email: "salem@example.com",
        phone: "+25191110055",
        region: "SNNPR",
        examResults: { mathematics: 178, english: 179, physics: 99, chemistry: 70, biology: 75, total: 601 },
        gender: "Female",
        disability: "none",
        photo: "https://randomuser.me/api/portraits/women/28.jpg",
        school: "St. Joseph School",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-057",
        dateOfBirth: new Date("2005-11-20"),
        studentNationalID: "1000000000057",
        firstName: "Mikiyas",
        lastName: "Abera",
        email: "mikiyas@example.com",
        phone: "+25191110057",
        region: "Sidama",
        examResults: { mathematics: 193, english: 171, physics: 79, chemistry: 90, biology: 79, total: 612 },
        gender: "Male",
        disability: "none",
        photo: "https://randomuser.me/api/portraits/men/29.jpg",
        school: "Bishoftu Preparatory",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-059",
        dateOfBirth: new Date("2005-02-07"),
        studentNationalID: "1000000000059",
        firstName: "Sara",
        lastName: "Asmamaw",
        email: "sara@example.com",
        phone: "+25191110059",
        region: "Dire Dawa",
        examResults: { mathematics: 177, english: 169, physics: 94, chemistry: 65, biology: 62, total: 567 },
        gender: "Female",
        disability: "visual",
        photo: "https://randomuser.me/api/portraits/women/30.jpg",
        school: "Fasiladas School",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-061",
        dateOfBirth: new Date("2005-07-07"),
        studentNationalID: "1000000000061",
        firstName: "Robel",
        lastName: "Bogale",
        email: "robel@example.com",
        phone: "+25191110061",
        region: "Tigray",
        examResults: { mathematics: 166, english: 185, physics: 81, chemistry: 62, biology: 84, total: 578 },
        gender: "Male",
        disability: "hearing",
        photo: "https://randomuser.me/api/portraits/men/31.jpg",
        school: "Kalamino Special High School",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-063",
        dateOfBirth: new Date("2004-02-18"),
        studentNationalID: "1000000000063",
        firstName: "Lidia",
        lastName: "Chala",
        email: "lidia@example.com",
        phone: "+25191110063",
        region: "Harari",
        examResults: { mathematics: 172, english: 178, physics: 72, chemistry: 68, biology: 95, total: 585 },
        gender: "Female",
        disability: "physical",
        photo: "https://randomuser.me/api/portraits/women/32.jpg",
        school: "Dire Dawa Preparatory",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-065",
        dateOfBirth: new Date("2004-11-25"),
        studentNationalID: "1000000000065",
        firstName: "Bereket",
        lastName: "Desta",
        email: "bereket@example.com",
        phone: "+25191110065",
        region: "Somali",
        examResults: { mathematics: 197, english: 171, physics: 99, chemistry: 84, biology: 94, total: 645 },
        gender: "Male",
        disability: "none",
        photo: "https://randomuser.me/api/portraits/men/33.jpg",
        school: "Hawassa Tabor",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-067",
        dateOfBirth: new Date("2003-01-02"),
        studentNationalID: "1000000000067",
        firstName: "Hanna",
        lastName: "Endale",
        email: "hanna@example.com",
        phone: "+25191110067",
        region: "Afar",
        examResults: { mathematics: 163, english: 182, physics: 70, chemistry: 85, biology: 86, total: 586 },
        gender: "Female",
        disability: "none",
        photo: "https://randomuser.me/api/portraits/women/34.jpg",
        school: "Yirgalem School",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-069",
        dateOfBirth: new Date("2005-10-17"),
        studentNationalID: "1000000000069",
        firstName: "Yonatan",
        lastName: "Fikadu",
        email: "yonatan@example.com",
        phone: "+25191110069",
        region: "Benshangul-Gumuz",
        examResults: { mathematics: 184, english: 161, physics: 94, chemistry: 99, biology: 62, total: 600 },
        gender: "Male",
        disability: "none",
        photo: "https://randomuser.me/api/portraits/men/35.jpg",
        school: "Ethio-Parents School",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-071",
        dateOfBirth: new Date("2005-01-19"),
        studentNationalID: "1000000000071",
        firstName: "Eden",
        lastName: "Getnet",
        email: "eden@example.com",
        phone: "+25191110071",
        region: "Gambela",
        examResults: { mathematics: 176, english: 166, physics: 90, chemistry: 87, biology: 67, total: 586 },
        gender: "Female",
        disability: "none",
        photo: "https://randomuser.me/api/portraits/women/36.jpg",
        school: "Bahir Dar Academy",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-073",
        dateOfBirth: new Date("2004-06-16"),
        studentNationalID: "1000000000073",
        firstName: "Natnael",
        lastName: "Hagos",
        email: "natnael@example.com",
        phone: "+25191110073",
        region: "Addis Ababa",
        examResults: { mathematics: 183, english: 164, physics: 74, chemistry: 64, biology: 78, total: 563 },
        gender: "Male",
        disability: "none",
        photo: "https://randomuser.me/api/portraits/men/37.jpg",
        school: "Addis Ababa University",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-075",
        dateOfBirth: new Date("2004-06-07"),
        studentNationalID: "1000000000075",
        firstName: "Saron",
        lastName: "Jima",
        email: "saron@example.com",
        phone: "+25191110075",
        region: "Oromia",
        examResults: { mathematics: 163, english: 171, physics: 83, chemistry: 70, biology: 60, total: 547 },
        gender: "Female",
        disability: "visual",
        photo: "https://randomuser.me/api/portraits/women/38.jpg",
        school: "Bahir Dar University",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-077",
        dateOfBirth: new Date("2004-11-17"),
        studentNationalID: "1000000000077",
        firstName: "Elias",
        lastName: "Kassahun",
        email: "elias@example.com",
        phone: "+25191110077",
        region: "Amhara",
        examResults: { mathematics: 161, english: 196, physics: 66, chemistry: 96, biology: 76, total: 595 },
        gender: "Male",
        disability: "hearing",
        photo: "https://randomuser.me/api/portraits/men/39.jpg",
        school: "Hawassa University",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-079",
        dateOfBirth: new Date("2005-02-05"),
        studentNationalID: "1000000000079",
        firstName: "Mahlet",
        lastName: "Lema",
        email: "mahlet@example.com",
        phone: "+25191110079",
        region: "SNNPR",
        examResults: { mathematics: 171, english: 179, physics: 66, chemistry: 72, biology: 73, total: 561 },
        gender: "Female",
        disability: "physical",
        photo: "https://randomuser.me/api/portraits/women/40.jpg",
        school: "St. Joseph School",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-081",
        dateOfBirth: new Date("2003-11-01"),
        studentNationalID: "1000000000081",
        firstName: "Amanuel",
        lastName: "Moges",
        email: "amanuel@example.com",
        phone: "+25191110081",
        region: "Sidama",
        examResults: { mathematics: 178, english: 188, physics: 76, chemistry: 63, biology: 97, total: 602 },
        gender: "Male",
        disability: "none",
        photo: "https://randomuser.me/api/portraits/men/41.jpg",
        school: "Bishoftu Preparatory",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-083",
        dateOfBirth: new Date("2003-05-23"),
        studentNationalID: "1000000000083",
        firstName: "Rediet",
        lastName: "Nigussie",
        email: "rediet@example.com",
        phone: "+25191110083",
        region: "Dire Dawa",
        examResults: { mathematics: 199, english: 177, physics: 64, chemistry: 68, biology: 64, total: 572 },
        gender: "Female",
        disability: "none",
        photo: "https://randomuser.me/api/portraits/women/42.jpg",
        school: "Fasiladas School",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-085",
        dateOfBirth: new Date("2004-03-09"),
        studentNationalID: "1000000000085",
        firstName: "Daniel",
        lastName: "Paulos",
        email: "daniel@example.com",
        phone: "+25191110085",
        region: "Tigray",
        examResults: { mathematics: 167, english: 166, physics: 60, chemistry: 64, biology: 79, total: 536 },
        gender: "Male",
        disability: "none",
        photo: "https://randomuser.me/api/portraits/men/43.jpg",
        school: "Kalamino Special High School",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-087",
        dateOfBirth: new Date("2004-10-13"),
        studentNationalID: "1000000000087",
        firstName: "Meron",
        lastName: "Retta",
        email: "meron@example.com",
        phone: "+25191110087",
        region: "Harari",
        examResults: { mathematics: 164, english: 177, physics: 68, chemistry: 88, biology: 62, total: 559 },
        gender: "Female",
        disability: "none",
        photo: "https://randomuser.me/api/portraits/women/44.jpg",
        school: "Dire Dawa Preparatory",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-089",
        dateOfBirth: new Date("2003-10-19"),
        studentNationalID: "1000000000089",
        firstName: "Yonas",
        lastName: "Seyoum",
        email: "yonas@example.com",
        phone: "+25191110089",
        region: "Somali",
        examResults: { mathematics: 164, english: 187, physics: 63, chemistry: 92, biology: 89, total: 595 },
        gender: "Male",
        disability: "none",
        photo: "https://randomuser.me/api/portraits/men/45.jpg",
        school: "Hawassa Tabor",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-091",
        dateOfBirth: new Date("2003-07-02"),
        studentNationalID: "1000000000091",
        firstName: "Frehiwot",
        lastName: "Tefera",
        email: "frehiwot@example.com",
        phone: "+25191110091",
        region: "Afar",
        examResults: { mathematics: 180, english: 193, physics: 63, chemistry: 68, biology: 97, total: 601 },
        gender: "Female",
        disability: "visual",
        photo: "https://randomuser.me/api/portraits/women/46.jpg",
        school: "Yirgalem School",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-093",
        dateOfBirth: new Date("2003-12-13"),
        studentNationalID: "1000000000093",
        firstName: "Surafel",
        lastName: "Wondimu",
        email: "surafel@example.com",
        phone: "+25191110093",
        region: "Benshangul-Gumuz",
        examResults: { mathematics: 187, english: 182, physics: 93, chemistry: 84, biology: 63, total: 609 },
        gender: "Male",
        disability: "hearing",
        photo: "https://randomuser.me/api/portraits/men/47.jpg",
        school: "Ethio-Parents School",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-095",
        dateOfBirth: new Date("2005-08-12"),
        studentNationalID: "1000000000095",
        firstName: "Feven",
        lastName: "Yosef",
        email: "feven@example.com",
        phone: "+25191110095",
        region: "Gambela",
        examResults: { mathematics: 198, english: 172, physics: 63, chemistry: 68, biology: 99, total: 600 },
        gender: "Female",
        disability: "physical",
        photo: "https://randomuser.me/api/portraits/women/48.jpg",
        school: "Bahir Dar Academy",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-097",
        dateOfBirth: new Date("2005-03-13"),
        studentNationalID: "1000000000097",
        firstName: "Yared",
        lastName: "Zewdu",
        email: "yared@example.com",
        phone: "+25191110097",
        region: "Addis Ababa",
        examResults: { mathematics: 161, english: 197, physics: 76, chemistry: 75, biology: 84, total: 593 },
        gender: "Male",
        disability: "none",
        photo: "https://randomuser.me/api/portraits/men/49.jpg",
        school: "Addis Ababa University",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-099",
        dateOfBirth: new Date("2005-08-15"),
        studentNationalID: "1000000000099",
        firstName: "Hewit",
        lastName: "Mengistu",
        email: "hewit@example.com",
        phone: "+25191110099",
        region: "Oromia",
        examResults: { mathematics: 177, english: 177, physics: 94, chemistry: 88, biology: 97, total: 633 },
        gender: "Female",
        disability: "none",
        photo: "https://randomuser.me/api/portraits/women/50.jpg",
        school: "Bahir Dar University",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      },
      {
        examID: "EXM-2024-101",
        dateOfBirth: new Date("2004-05-22"),
        studentNationalID: "1000000000101",
        firstName: "Dawit",
        lastName: "Abebe",
        email: "dawit@example.com",
        phone: "+25191110101",
        region: "Amhara",
        examResults: { mathematics: 196, english: 193, physics: 96, chemistry: 63, biology: 76, total: 624 },
        gender: "Male",
        disability: "none",
        photo: "https://randomuser.me/api/portraits/men/51.jpg",
        school: "Hawassa University",
        academicYear: "2024",
        isRegistered: false,
        status: "PASS"
      }
    ]

    for (const student of students) {
      console.log(`📝 Importing: ${student.firstName} ${student.lastName} (${student.examID})`)
      await prisma.student.create({ data: student })
    }

    const count = await prisma.student.count()
    console.log(`✅ Successfully imported ${count} students!`)

    // Show example
    const example = await prisma.student.findFirst({
      where: { examID: "EXM-2024-003" }
    })
    if (example) {
      console.log('\n📊 Example student (EXM-2024-003):')
      console.log(JSON.stringify(example.examResults, null, 2))
    }

  } catch (error) {
    console.error('❌ Error:', error)
  } finally {
    await prisma.$disconnect()
  }
}

main()